CREATE TABLE IF NOT EXISTS "user" (
    id UUID PRIMARY KEY,
    "name" varchar,
    username varchar,
    password varchar,
    email varchar,
    email_verified boolean,
    bio varchar,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz,
    deactivated_at timestamptz,
    deleted_at timestamptz,
    last_seen timestamptz,
    ip_address varchar(48),
    user_agent varchar,
    "role" varchar,
    gender VARCHAR(20),
    avatar_asset_id bigint,
    country_code varchar(20),
    phone_number varchar(20),
    location varchar,
    nationality varchar,
    national_id_number varchar,
    "language" varchar,
    birthdate date,
    UNIQUE(username),
    UNIQUE(email)
);